apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-qqm8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-qqm8@sha256:be6423d4ebe94fbf30c94ed510a20d41b8ac2ace20f49c061d01b76ac9dee23e
        name: my-nodejs
        resources: {}
status: {}
